apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ngozi-certificate
  namespace: sock-shop
spec:
  secretName: ngozionwuka
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sockshop.ngozionwuka.me
  dnsNames:
  - sockshop.ngozionwuka.me